#######################################################
# Copyright 2016 Web of Objects project All Rights Reserved.
# Author: Khaled Q. AbdelFadeel <kqorany2@gmail.com> and Khaled F. Elsayed <kelsayed@gmail.com>
#
#
#       Build IP adapter for esp8266
#######################################################

Import('env', 'src_dir')
import os.path

env.AppendUnique(CPPPATH = [ os.path.join(src_dir, 'esp8266') ])

if env.get('SHIELD') == 'WIFI':
    src_files = [ 'caipclient_wifi.cpp',
                   'caipserver_wifi.cpp',
                   'caipnwmonitor_wifi.cpp' ]

Return('src_files')
